const express = require('express');
const { authMiddleware, requirePermission, requireRole } = require('../../shared');
const controller = require('../controllers/order.controller');

const router = express.Router();

router.get('/health', controller.health);
router.get('/cart', authMiddleware, controller.cartList);
router.post('/cart/add', authMiddleware, controller.cartAdd);
router.put('/cart/:id', authMiddleware, controller.cartUpdate);
router.delete('/cart/:id', authMiddleware, controller.cartDelete);
router.delete('/cart/clear', authMiddleware, controller.cartClear);
router.get('/', authMiddleware, controller.list);
router.post('/', authMiddleware, controller.create);
router.post('/payment/callback/:provider', controller.paymentCallback);
router.post('/refund/callback/:provider', controller.refundCallback);
router.post('/payment/mock', authMiddleware, controller.mockPayment);
router.get('/payment/:orderId/status', authMiddleware, controller.paymentStatus);
router.get('/payment/history', authMiddleware, controller.paymentHistory);
router.post('/refunds', authMiddleware, controller.requestRefund);
router.post('/refunds/:id/evidence/upload-intent', authMiddleware, controller.createRefundEvidenceUploadIntent);
router.post('/refunds/:id/evidence', authMiddleware, controller.addRefundEvidence);
router.post('/refunds/evidence/scan/callback', controller.refundEvidenceScanCallback);
router.get('/refunds', authMiddleware, requireRole('admin', 'merchant'), requirePermission('refund:list'), controller.refundList);
router.get('/refunds/export-placeholder', authMiddleware, requireRole('admin', 'merchant'), requirePermission('refund:list'), controller.refundExportPlaceholder);
router.get('/refunds/evidence/retention/cleanup-dry-run', authMiddleware, requireRole('admin'), requirePermission('refund:review'), controller.refundEvidenceRetentionCleanupDryRun);
router.put('/refunds/evidence/:evidenceId/scan', authMiddleware, requireRole('admin'), requirePermission('refund:review'), controller.updateRefundEvidenceScan);
router.put('/refunds/:id/review', authMiddleware, requireRole('admin', 'merchant'), requirePermission('refund:review'), controller.reviewRefund);
router.get('/refunds/:id', authMiddleware, requireRole('admin', 'merchant'), requirePermission('refund:detail'), controller.refundDetail);
router.get('/fulfillment/orders', authMiddleware, requireRole('admin', 'merchant'), requirePermission('order:ship'), controller.fulfillmentList);
router.get('/exports/jobs', authMiddleware, requireRole('admin', 'merchant'), requirePermission('export:manage'), controller.exportJobList);
router.post('/exports/jobs', authMiddleware, requireRole('admin', 'merchant'), requirePermission('export:manage'), controller.exportJobCreate);
router.get('/operations/logs', authMiddleware, requireRole('admin', 'merchant'), requirePermission('operation:log:list'), controller.operationLogList);
router.get('/logistics/:orderId', authMiddleware, controller.logistics);
router.put('/:id/ship', authMiddleware, requireRole('admin', 'merchant'), requirePermission('order:ship'), controller.ship);
router.get('/:id', authMiddleware, controller.detail);
router.put('/:id/cancel', authMiddleware, controller.cancel);
router.put('/:id/confirm', authMiddleware, controller.confirm);

module.exports = router;
